### ISSUE TITLE
Get pod logs when multiple containers are used

### ISSUE THREAD

**Issue by etorres** [LamaAni/KubernetesJobOperator#38]
### In short:

Hi,

We are using `KubernetesLegacyJobOperator` to manage our Spark-based applications with Airflow. In our setup we are allocating two containers (spark-kubernetes-driver and fluent-bit) within the same pod and this is causing the following error:

```
airflow_kubernetes_job_operator.kube_api.queries.GetPodLogs, Bad Request: a container name must be specified for pod application-name, choose one of: [spark-kubernetes-driver fluent-bit]
```

We managed to make it work by setting the value of the `get_logs` parameter to `False`, but we would like to have access to the logs in the airflow task.

Is there any way to get this? I looked for but I had no luck finding an answer.

Thanks in advance!

### More information

A fragment of the stack trace:

kubernetes.client.exceptions.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'cef97a1d-ee58-4bc1-b220-63338af4f3ee', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Mon, 26 Apr 2021 11:14:05 GMT', 'Content-Length': '259'})
HTTP response body: {'kind': 'Status', 'apiVersion': 'v1', 'metadata': {}, 'status': 'Failure', 'message': 'a container name must be specified for pod application-y761881y, choose one of: [spark-kubernetes-driver fluent-bit]', 'reason': 'BadRequest', 'code': 400}

**Comment by LamaAni** [comment]
Hi, Thank you for posting!

Would love to help but I would need an example dag, with minimal configuration if you can.

This seems like an error where a pod has multiple containers. Is that correct?

I'm not sure about the timeline, but I'm pretty confident we can resolve this issue.

**Comment by LamaAni** [comment]
Hi, I was able to reproduce your error with (`testpod.py`), 
```python
from airflow import DAG
from airflow_kubernetes_job_operator import KubernetesJobOperator
from airflow.utils.dates import days_ago

default_args = {
    "depends_on_past": False,
    "start_date": days_ago(1),
}

dag = DAG(dag_id="test_multi_container", default_args=default_args, schedule_interval=None)

with dag:
    KubernetesJobOperator(
        task_id="test-multi-container",
        body_filepath="./testdag.yaml",
    )

if __name__ == "__main__":
    dag.schedule_interval = None
    dag.clear()
    dag.run()
```
Job configuration (`testpod.yaml`):
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: 'multi-container-test'
  labels:
    app: 'multi-container-test'
spec:
  restartPolicy: Never
  containers:
    - name: container1
      image: 'alpine:latest'
      command:
        - sh
        - -c
        - |
          echo starting sleep...
          sleep 10
          echo end
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 200Mi
    - name: container2
      image: 'alpine:latest'
      command:
        - sh
        - -c
        - |
          echo starting sleep...
          sleep 10
          echo end
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 200Mi
```
